---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd-jenkins
  namespace: default
  labels:
    app: jenkins
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-deploy
subjects:
- kind: ServiceAccount
  name: cd-jenkins
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: Namespace
apiVersion: v1
metadata:
  name: production
  labels:
    app: gceme
